name: Deploy Frontend to Azure Storage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Deploy to Azure Storage'
        run: |
          az storage blob upload-batch \
            --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            --account-key "${{ secrets.AZURE_STORAGE_KEY }}" \
            --destination '$web' \
            --source ./habitat-ai-backend/frontend \
            --overwrite true
