name: Deploy Frontend to Azure Storage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Deploy to Azure Storage'
        uses: Azure/storage-deploy@v1
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          source-path: 'habitat-ai-backend/frontend'
          container-name: '$web'
          strip-components: 1 # This ensures index.html is in the root of $web, not inside a folder
